[meta]
version = "26.2"
loader = "fabric"

[strings]
server_mods_header = "### Серверные моды"
server_mods_description = "Установка этих модов на клиент **НЕ ТРЕБУЕТСЯ**, но они работают на сервере."
server_loader_mods_header = "#### Fabric-моды"
server_datapacks_header = "#### Дата-паки"
required_mods_header = "### Обязательные моды"
required_mods_description = "Эти моды **ОБЯЗАТЕЛЬНЫ** к установке на клиент для стабильной игры на сервере."
recommended_mods_header = "### Рекомендуемые моды"
recommended_mods_description = "Эти клиентские моды не обязательны, чтобы зайти на сервер, но улучшают игровой опыт. Вы можете пополнить этот список удобными вам клиентскими модами или исключить ненужные для вашей сборки."
optional_mods_header = "### Опциональные моды"
optional_mods_description = "Это клиентсие моды ситуативны, но поддерживаются сервером."

# СЕРВЕРНЫЕ МОДЫ

[[list.server]]
name = "2032-world-height"
source = "modrinth"
version = "1.3+mod"
type = "general"
description = "увеличивает максимальную высоту строительства до 2032 блоков"

[[list.server]]
name = "appleskin"
source = "modrinth"
version = "3.0.10+mc26.2"
type = "general"
description = "улучшение интерфейса здоровья и голода (серверная часть)"

[[list.server]]
name = "auth"
source = "modrinth"
version = "v1.6.2+mod"
type = "general"
description = "авторизация по паролю"

[[list.server]]
name = "chunky"
source = "modrinth"
version = "1.5.3"
type = "general"
description = "инструмент для генерации чанков"

[[list.server]]
name = "distanthorizons"
source = "modrinth"
version = "3.2.0-b-26.2"
type = "general"
description = "далёкая прорисовка чанков с оптимизациями (серверная часть)"

[[list.server]]
name = "immersive-paintings"
source = "modrinth"
version = "0.7.8+26.2"
type = "general"
description = "мод для добавления кастомных картин (серверная часть)"

[[list.server]]
name = "invisible-frames-mod"
source = "modrinth"
version = "2.0.1+26.2-fabric"
type = "general"
description = "возможность сделать рамку невидимой через Shift+ПКМ"

[[list.server]]
name = "jei"
source = "modrinth"
version = "30.16.0.124"
type = "general"
description = "браузер рецептов (клиентская часть)"

[[list.server]]
name = "ledger"
source = "modrinth"
version = "1.3.23"
type = "general"
description = "логирование всех событий на сервере"

[[list.server]]
name = "rwsheld-mod"
pretty_name = "RW Sheld Mod"
download_link = "https://github.com/SpdrSO/rwsheld-mod/releases/download/v1.4.0/rwsheld-mod-1.4.0+26.2.jar"
type = "general"
description = "кастомный мод для нашего сервера"

[[list.server]]
name = "set-world-spawn-point"
source = "modrinth"
version = "26.2.0-3.8-fabric+forge+neo"
type = "general"
description = "конкретная точка респавна"

[[list.server]]
name = "shulkerboxtooltip"
source = "modrinth"
version = "5.4.0+26.2-fabric"
type = "general"
description = "предпросмотр предметов в шалкере (серверная часть)"

[[list.server]]
name = "skinrestorer"
source = "modrinth"
version = "2.10.0+26.1-fabric"
type = "general"
description = "подтягивает скины по нику с серверов Mojang и по команде `/skin` с Ely.by"

[[list.server]]
name = "spark"
source = "modrinth"
version = "1.10.173-fabric"
type = "general"
description = "анализ нагрузки на сервер"

[[list.server]]
name = "simple-voice-chat"
source = "modrinth"
version = "fabric-2.6.22+26.2"
type = "general"
description = "голосовой чат (серверная часть)"

[[list.server]]
name = "worldedit"
source = "modrinth"
version = "7.4.4"
type = "general"
description = "инструмент для редактирования мира"

# ОПТИМИЗАЦИЯ СЕРВЕРА

[[list.server]]
name = "clumps"
source = "modrinth"
version = "26.2.1"
type = "optimization"

[[list.server]]
name = "ferrite-core"
source = "modrinth"
version = "9.0.0-fabric"
type = "optimization"

[[list.server]]
name = "krypton"
source = "modrinth"
version = "0.3.1"
type = "optimization"

[[list.server]]
name = "lithium"
source = "modrinth"
version = "mc26.2-0.25.3-fabric"
type = "optimization"

[[list.server]]
name = "modernfix-mvus"
source = "modrinth"
version = "5.27.19-build.1"
type = "optimization"

# ЗАВИСИМОСТИ СЕРВЕРНЫХ МОДОВ

[[list.server]]
name = "collective"
source = "modrinth"
version = "26.2.0-8.39-fabric+forge+neo"
type = "dependency"

[[list.server]]
name = "fabric-api"
source = "modrinth"
version = "0.158.0+26.2"
type = "dependency"

[[list.server]]
name = "fabric-language-kotlin"
source = "modrinth"
version = "1.13.13+kotlin.2.4.10"
type = "dependency"

[[list.server]]
name = "fzzy-config"
source = "modrinth"
version = "0.7.6+26.2"
type = "dependency"

# ОБЯЗАТЕЛЬНЫЕ МОДЫ

[[list.required]]
name = "immersive-paintings"
source = "modrinth"
version = "0.7.8+26.2"
type = "general"
description = "мод для добавления кастомных картин (клиентская часть)"

[[list.required]]
name = "simple-voice-chat"
source = "modrinth"
version = "fabric-2.6.22+26.2"
type = "general"
description = "голосовой чат (клиентская часть)"

[[list.required]]
name = "fabric-api"
source = "modrinth"
version = "0.158.0+26.2"
type = "dependency"

[[list.required]]
name = "fabric-language-kotlin"
source = "modrinth"
version = "1.13.13+kotlin.2.4.10"
type = "dependency"

[[list.required]]
name = "fzzy-config"
source = "modrinth"
version = "0.7.6+26.2"
type = "dependency"

# РЕКОМЕНДУЕМЫЕ МОДЫ

[[list.recommended]]
name = "appleskin"
source = "modrinth"
version = "3.0.10+mc26.2"
type = "general"
description = "улучшение интерфейса здоровья и голода (клиентская часть)"

[[list.recommended]]
name = "chat-heads"
source = "modrinth"
version = "1.2.5"
type = "general"
description = "отображение аватарок игроков в чате"

[[list.recommended]]
name = "continuity"
source = "modrinth"
version = "3.0.1+26.2"
type = "general"
description = "соединённые текстуры стекла и некоторых других строительных блоков (требуется активировать встроенный ресурспаки)"

[[list.recommended]]
name = "jei"
source = "modrinth"
version = "30.16.0.124"
type = "general"
description = "браузер рецептов (клиентская часть)"

[[list.recommended]]
name = "lambdynamiclights"
source = "modrinth"
version = "4.12.2+26.2"
type = "general"
description = "доработка освещения"

[[list.recommended]]
name = "modmenu"
source = "modrinth"
version = "20.0.1"
type = "general"
description = "меню настройки модов"

[[list.recommended]]
name = "shulkerboxtooltip"
source = "modrinth"
version = "5.4.0+26.2-fabric"
type = "general"
description = "предпросмотр предметов в шалкере (клиентская часть)"

[[list.recommended]]
name = "xaeros-minimap"
source = "modrinth"
version = "fabric-26.2-26.4.2"
type = "general"
description = "миникарта и маркеры места смерти"

[[list.recommended]]
name = "xaeros-world-map"
source = "modrinth"
version = "fabric-26.2-1.44.2"
type = "general"
description = "полноэкранная карта мира"

[[list.recommended]]
name = "zoomify"
source = "modrinth"
version = "2.16.1+26.2"
type = "general"
description = "зум на клавишу C"

# ОПТИМИЗАЦИЯ КЛИЕНТА

[[list.recommended]]
name = "ferrite-core"
source = "modrinth"
version = "9.0.0-fabric"
type = "optimization"

[[list.recommended]]
name = "lithium"
source = "modrinth"
version = "mc26.2-0.25.3-fabric"
type = "optimization"

[[list.recommended]]
name = "sodium"
source = "modrinth"
version = "mc26.2-0.9.1-fabric"
type = "optimization"

# ЗАВИСИМОСТИ РЕКОМЕНДУЕМЫХ МОДОВ

[[list.recommended]]
name = "fabric-api"
source = "modrinth"
version = "0.158.0+26.2"
type = "dependency"

[[list.recommended]]
name = "fabric-language-kotlin"
source = "modrinth"
version = "1.13.13+kotlin.2.4.10"
type = "dependency"

[[list.recommended]]
name = "placeholder-api"
source = "modrinth"
version = "3.1.0-beta.1+26.2"
type = "dependency"

[[list.recommended]]
name = "yacl"
source = "modrinth"
version = "3.9.6+26.2-fabric"
type = "dependency"

# ОПЦИОНАЛЬНЫЕ МОДЫ

[[list.optional]]
name = "distanthorizons"
source = "modrinth"
version = "3.2.0-b-26.2"
type = "general"
description = "далёкая прорисовка чанков с оптимизациями (клиентская часть)"

[[list.optional]]
name = "iris"
source = "modrinth"
version = "1.11.2+26.2-fabric"
type = "general"
description = "поддержка шейдеров"

[[list.optional]]
name = "fabric-api"
source = "modrinth"
version = "0.158.0+26.2"
type = "dependency"

[[list.optional]]
name = "sodium"
source = "modrinth"
version = "mc26.2-0.9.1-fabric"
type = "dependency"
